# docker-compose.yml
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: fastapi
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d fastapi"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://app:app@db:5432/fastapi
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ./logs:/app/logs

  prometheus:
    image: prom/prometheus
    volumes:
      # host dir → container dir
      - ./monitoring:/etc/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports: ["3000:3000"]
    depends_on: [prometheus]