[project]
name = "fastapi-demo"
version = "0.1.0"
description = "fastapi_demo"
authors = [
    {name = "Denis Połyncew"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi (>=0.115.14,<0.116.0)",
    "uvicorn[standard] (>=0.35.0,<0.36.0)",
    "sqlmodel (>=0.0.24,<0.0.25)",
    "asyncpg (>=0.30.0,<0.31.0)",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
    "pytest-asyncio (>=1.0.0,<2.0.0)"
]
packages = [
  { include = "app" }
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
alembic = "^1.16.2"
pytest = "^8.4.1"
aiosqlite = "^0.21.0"

