global:
  scrape_interval: 15s        # how often to pull metrics
  evaluation_interval: 15s    # how often to run rules (none yet)

scrape_configs:
  # ── 1. scrape the FastAPI service ─────────────────────
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"] 

  # ── 2. scrape Prometheus itself ───────────────────────
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
